
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.player
{
public sealed partial class PlayerAnimatorConfig : Luban.BeanBase
{
    public PlayerAnimatorConfig(ByteBuf _buf) 
    {
        Key = _buf.ReadInt();
        AnimatorName = _buf.ReadString();
        AnimatorType = (player.PlayerAnimatorType)_buf.ReadInt();
        Animator01 = _buf.ReadString();
        IsSpecialAnimator = _buf.ReadBool();
        IsOccupyTwoHats = _buf.ReadBool();
        IsMultipleLayers = _buf.ReadBool();
        Animator02 = _buf.ReadString();
    }

    public static PlayerAnimatorConfig DeserializePlayerAnimatorConfig(ByteBuf _buf)
    {
        return new player.PlayerAnimatorConfig(_buf);
    }

    /// <summary>
    /// 动画索引
    /// </summary>
    public readonly int Key;
    /// <summary>
    /// 动画名称
    /// </summary>
    public readonly string AnimatorName;
    /// <summary>
    /// 动画类别
    /// </summary>
    public readonly player.PlayerAnimatorType AnimatorType;
    /// <summary>
    /// 动画控制器名称
    /// </summary>
    public readonly string Animator01;
    /// <summary>
    /// 是否是特殊动画
    /// </summary>
    public readonly bool IsSpecialAnimator;
    /// <summary>
    /// 是否占据两个饰品位置
    /// </summary>
    public readonly bool IsOccupyTwoHats;
    /// <summary>
    /// 是否两个图层
    /// </summary>
    public readonly bool IsMultipleLayers;
    /// <summary>
    /// 第二个图层动画名称
    /// </summary>
    public readonly string Animator02;
   
    public const int __ID__ = 1989072727;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "animatorName:" + AnimatorName + ","
        + "animatorType:" + AnimatorType + ","
        + "animator01:" + Animator01 + ","
        + "isSpecialAnimator:" + IsSpecialAnimator + ","
        + "isOccupyTwoHats:" + IsOccupyTwoHats + ","
        + "isMultipleLayers:" + IsMultipleLayers + ","
        + "animator02:" + Animator02 + ","
        + "}";
    }
}

}

