
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.player
{ 
    public enum PlayerAnimatorType
    {
        /// <summary>
        /// 头发动画控制器
        /// </summary>
        HAIR = 0,
        /// <summary>
        /// 脸部动画控制器
        /// </summary>
        FACE = 1,
        /// <summary>
        /// 衣服动画控制器
        /// </summary>
        CLOTHES = 2,
        /// <summary>
        /// 裤子动画控制器
        /// </summary>
        TROUSERS = 3,
        /// <summary>
        /// 身体动画控制器
        /// </summary>
        BODY = 4,
        /// <summary>
        /// 腿部动画控制器
        /// </summary>
        LEGS = 5,
        /// <summary>
        /// 饰品一动画控制器
        /// </summary>
        JEWELRYFIRST = 7,
        /// <summary>
        /// 饰品二动画控制器
        /// </summary>
        JEWELRYSECOND = 8,
        /// <summary>
        /// 工具动画控制器
        /// </summary>
        TOOL = 6,
    }

} 

