
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.player
{
public partial class TbPlayerAnimatorConfig
{
    private readonly System.Collections.Generic.Dictionary<int, player.PlayerAnimatorConfig> _dataMap;
    private readonly System.Collections.Generic.List<player.PlayerAnimatorConfig> _dataList;
    
    public TbPlayerAnimatorConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, player.PlayerAnimatorConfig>();
        _dataList = new System.Collections.Generic.List<player.PlayerAnimatorConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            player.PlayerAnimatorConfig _v;
            _v = player.PlayerAnimatorConfig.DeserializePlayerAnimatorConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, player.PlayerAnimatorConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<player.PlayerAnimatorConfig> DataList => _dataList;

    public player.PlayerAnimatorConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public player.PlayerAnimatorConfig Get(int key) => _dataMap[key];
    public player.PlayerAnimatorConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

