
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BubbleType
    {
        /// <summary>
        /// 普通泡泡
        /// </summary>
        NormalBubble = 0,
        /// <summary>
        /// 可戳破泡泡
        /// </summary>
        PoppingBubble = 1,
    }

} 

