
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class LevelConfig : Luban.BeanBase
{
    public LevelConfig(ByteBuf _buf) 
    {
        Index = _buf.ReadString();
        Type = (BubbleType)_buf.ReadInt();
        Context = _buf.ReadString();
        StartEvent = _buf.ReadString();
        EndEvent = _buf.ReadString();
    }

    public static LevelConfig DeserializeLevelConfig(ByteBuf _buf)
    {
        return new LevelConfig(_buf);
    }

    /// <summary>
    /// 关卡，例如2-1-3，即第二关第一句话第三个词语
    /// </summary>
    public readonly string Index;
    /// <summary>
    /// 泡泡类型，0为普通泡泡，1为可戳破泡泡
    /// </summary>
    public readonly BubbleType Type;
    /// <summary>
    /// 泡泡文字内容
    /// </summary>
    public readonly string Context;
    /// <summary>
    /// 泡泡开始事件
    /// </summary>
    public readonly string StartEvent;
    /// <summary>
    /// 泡泡结束事件
    /// </summary>
    public readonly string EndEvent;
   
    public const int __ID__ = -1308229690;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "type:" + Type + ","
        + "context:" + Context + ","
        + "startEvent:" + StartEvent + ","
        + "endEvent:" + EndEvent + ","
        + "}";
    }
}

}

