
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class tbLevelConfig
{
    private readonly System.Collections.Generic.Dictionary<string, LevelConfig> _dataMap;
    private readonly System.Collections.Generic.List<LevelConfig> _dataList;
    
    public tbLevelConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, LevelConfig>();
        _dataList = new System.Collections.Generic.List<LevelConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            LevelConfig _v;
            _v = LevelConfig.DeserializeLevelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Index, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, LevelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<LevelConfig> DataList => _dataList;

    public LevelConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LevelConfig Get(string key) => _dataMap[key];
    public LevelConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

